### ISSUE TITLE
implement scaffolded methods in CL_I18N_LANGUAGES

### ISSUE THREAD

**Issue by larshp** [open-abap/open-abap#382]
just hardcode the list of languages

add unit tests

**Comment by g-back** [comment]
I can try this,
you say hardcode, so I would make an ITAB with the language info and just do a read table.
I don't know what "scaffolded methods" means, does that mean the methods that are already implemented in the class (with todo comments)?

**Comment by larshp** [comment]
see https://github.com/open-abap/open-abap/blob/9236a236bbdbdfebaf54942e11c476b74a8bf213/src/cl_i18n_languages.clas.abap#L21

1: add some more languages in method `sap1_to_sap2` using the CASE approach, it does not have to be everything
2: implement method `sap2_to_iso639_1` similar to `sap1_to_sap2`
